[build]
builder = "NIXPACKS"
buildCommand = "export PATH=/root/.nix-profile/bin:$PATH && export JAVA_HOME=$(dirname $(dirname $(readlink -f $(which java)))) && java -version && javac -version && mvn -version && mvn clean package -DskipTests -B"

[build.outputs]
paths = ["stockflow-backend-web-api/target/*.jar"]

[phases.setup]
nixPkgs = ["jdk21_headless", "maven"]

[deploy]
startCommand = "java -jar stockflow-backend-web-api/target/stockflow-backend-web-api-1.0-SNAPSHOT.jar"
restartPolicyType = "ON_FAILURE"

# Forzar la versión de Java
[variables]
  NIXPACKS_JDK_VERSION = "21"
  NIXPACKS_JAVA_VERSION = "21"
